// Scripture URL mapping - handles abbreviated forms with periods
const scriptureUrlMap = {
    // Old Testament
    'Genesis': 'gen',
    'Gen': 'gen',
    'Gen.': 'gen',
    'Exodus': 'ex',
    'Ex': 'ex',
    'Ex.': 'ex',
    'Leviticus': 'lev',
    'Lev': 'lev',
    'Lev.': 'lev',
    'Numbers': 'num',
    'Num': 'num',
    'Num.': 'num',
    'Deuteronomy': 'deut',
    'Deut': 'deut',
    'Deut.': 'deut',
    'Joshua': 'josh',
    'Josh': 'josh',
    'Josh.': 'josh',
    'Judges': 'judg',
    'Judg': 'judg',
    'Judg.': 'judg',
    'Ruth': 'ruth',
    '1 Samuel': '1-sam',
    '1 Sam': '1-sam',
    '1 Sam.': '1-sam',
    '2 Samuel': '2-sam',
    '2 Sam': '2-sam',
    '2 Sam.': '2-sam',
    '1 Kings': '1-kgs',
    '1 Kgs': '1-kgs',
    '1 Kgs.': '1-kgs',
    '2 Kings': '2-kgs',
    '2 Kgs': '2-kgs',
    '2 Kgs.': '2-kgs',
    '1 Chronicles': '1-chr',
    '1 Chr': '1-chr',
    '1 Chr.': '1-chr',
    '2 Chronicles': '2-chr',
    '2 Chr': '2-chr',
    '2 Chr.': '2-chr',
    'Ezra': 'ezra',
    'Nehemiah': 'neh',
    'Neh': 'neh',
    'Neh.': 'neh',
    'Esther': 'esth',
    'Esth': 'esth',
    'Esth.': 'esth',
    'Job': 'job',
    'Psalms': 'ps',
    'Ps': 'ps',
    'Ps.': 'ps',
    'Proverbs': 'prov',
    'Prov': 'prov',
    'Prov.': 'prov',
    'Ecclesiastes': 'eccl',
    'Eccl': 'eccl',
    'Eccl.': 'eccl',
    'Song of Solomon': 'song',
    'Song': 'song',
    'Isaiah': 'isa',
    'Isa': 'isa',
    'Isa.': 'isa',
    'Jeremiah': 'jer',
    'Jer': 'jer',
    'Jer.': 'jer',
    'Lamentations': 'lam',
    'Lam': 'lam',
    'Lam.': 'lam',
    'Ezekiel': 'ezek',
    'Ezek': 'ezek',
    'Ezek.': 'ezek',
    'Daniel': 'dan',
    'Dan': 'dan',
    'Dan.': 'dan',
    'Hosea': 'hosea',
    'Joel': 'joel',
    'Amos': 'amos',
    'Obadiah': 'obad',
    'Obad': 'obad',
    'Obad.': 'obad',
    'Jonah': 'jonah',
    'Micah': 'micah',
    'Nahum': 'nahum',
    'Habakkuk': 'hab',
    'Hab': 'hab',
    'Hab.': 'hab',
    'Zephaniah': 'zeph',
    'Zeph': 'zeph',
    'Zeph.': 'zeph',
    'Haggai': 'hag',
    'Hag': 'hag',
    'Hag.': 'hag',
    'Zechariah': 'zech',
    'Zech': 'zech',
    'Zech.': 'zech',
    'Malachi': 'mal',
    'Mal': 'mal',
    'Mal.': 'mal',
    // New Testament
    'Matthew': 'matt',
    'Matt': 'matt',
    'Matt.': 'matt',
    'Mark': 'mark',
    'Luke': 'luke',
    'John': 'john',
    'Acts': 'acts',
    'Romans': 'rom',
    'Rom': 'rom',
    'Rom.': 'rom',
    '1 Corinthians': '1-cor',
    '1 Cor': '1-cor',
    '1 Cor.': '1-cor',
    '2 Corinthians': '2-cor',
    '2 Cor': '2-cor',
    '2 Cor.': '2-cor',
    'Galatians': 'gal',
    'Gal': 'gal',
    'Gal.': 'gal',
    'Ephesians': 'eph',
    'Eph': 'eph',
    'Eph.': 'eph',
    'Philippians': 'philip',
    'Philip': 'philip',
    'Philip.': 'philip',
    'Colossians': 'col',
    'Col': 'col',
    'Col.': 'col',
    '1 Thessalonians': '1-thes',
    '1 Thes': '1-thes',
    '1 Thes.': '1-thes',
    '2 Thessalonians': '2-thes',
    '2 Thes': '2-thes',
    '2 Thes.': '2-thes',
    '1 Timothy': '1-tim',
    '1 Tim': '1-tim',
    '1 Tim.': '1-tim',
    '2 Timothy': '2-tim',
    '2 Tim': '2-tim',
    '2 Tim.': '2-tim',
    'Titus': 'titus',
    'Philemon': 'philem',
    'Philem': 'philem',
    'Philem.': 'philem',
    'Hebrews': 'heb',
    'Heb': 'heb',
    'Heb.': 'heb',
    'James': 'james',
    '1 Peter': '1-pet',
    '1 Pet': '1-pet',
    '1 Pet.': '1-pet',
    '2 Peter': '2-pet',
    '2 Pet': '2-pet',
    '2 Pet.': '2-pet',
    '1 John': '1-jn',
    '1 Jn': '1-jn',
    '1 Jn.': '1-jn',
    '2 John': '2-jn',
    '2 Jn': '2-jn',
    '2 Jn.': '2-jn',
    '3 John': '3-jn',
    '3 Jn': '3-jn',
    '3 Jn.': '3-jn',
    'Jude': 'jude',
    'Revelation': 'rev',
    'Rev': 'rev',
    'Rev.': 'rev',
    // Book of Mormon
    '1 Nephi': '1-ne',
    '1 Ne': '1-ne',
    '1 Ne.': '1-ne',
    '2 Nephi': '2-ne',
    '2 Ne': '2-ne',
    '2 Ne.': '2-ne',
    '3 Nephi': '3-ne',
    '3 Ne': '3-ne',
    '3 Ne.': '3-ne',
    '4 Nephi': '4-ne',
    '4 Ne': '4-ne',
    '4 Ne.': '4-ne',
    'Jacob': 'jacob',
    'Enos': 'enos',
    'Jarom': 'jarom',
    'Omni': 'omni',
    'Words of Mormon': 'w-of-m',
    'W of M': 'w-of-m',
    'Mosiah': 'mosiah',
    'Alma': 'alma',
    'Helaman': 'hel',
    'Hel': 'hel',
    'Hel.': 'hel',
    'Mormon': 'morm',
    'Morm': 'morm',
    'Morm.': 'morm',
    'Ether': 'ether',
    'Moroni': 'moro',
    'Moro': 'moro',
    'Moro.': 'moro',
    // Doctrine and Covenants
    'D&C': 'dc',
    'Doctrine and Covenants': 'dc',
    // Pearl of Great Price
    'Moses': 'moses',
    'Abraham': 'abr',
    'Abr': 'abr',
    'Abr.': 'abr',
    'Joseph Smith—Matthew': 'js-m',
    'JS—M': 'js-m',
    'Joseph Smith—History': 'js-h',
    'JS—H': 'js-h',
    'Articles of Faith': 'a-of-f',
    'A of F': 'a-of-f'
};
